server:
  error:
    include-message: always

spring:
  codec:
    max-in-memory-size: 5MB
  redis:
    host: localhost
    port: 6379

trustpilot:
  base-url: https://www.trustpilot.com
  review-url: ${trustpilot.base-url}/review/
  timeout-sec: 3
  cache-ttl-sec: 3600
  default-error-message: "Please contact belnarto@gmail.com for this error"
